### ISSUE TITLE
ModuleNotFoundError: No module named 'ultrasound_vid.utils.video_visualizer'

### ISSUE THREAD

**Issue by cgnerds** [HaojunYu1998/UltraDet#1]
Can you kindly tell me how to solve this problem? Thank you very much!

**Comment by xjtulyc** [comment]
Thank you for bringing this to our attention. We apologize for the oversight in the ``UltraDet/ultrasound_vid/modeling/heads/__init__.py`` file, where some unrelated visualization code was not removed. We have already fixed this issue in our GitHub repository.

**Comment by HaojunYu1998** [comment]
The commit 7baa62c has fixed this bug. So I close this issue.
