### ISSUE TITLE
The results in the paper.

### ISSUE THREAD

**Issue by Q0409** [HaojunYu1998/UltraDet#11]
Hello, may I ask if the results in the paper are the average of the outcomes from the four models that were trained individually through fourfold cross-validation on the test set?

**Comment by xjtulyc** [comment]
Hello,

Thank you for your inquiry. In our paper, the results presented in Table 1 reflect the performance of UltraDet compared to other real-time detectors. We conducted 4-fold cross-validation, and the reported results are the mean values along with standard errors derived from these folds on the test set to reduce any potential fluctuations.

Specifically, UltraDet demonstrates superior performance in terms of precision and false positive (FP) rates. For example, the Precision at 90% recall (Pr90) of UltraDet reaches 90.8%, which is an absolute improvement of 5.4% over the next best competitor, PTSEFormer. Additionally, the false positives per sequence per minute (FP90) for UltraDet are reduced by approximately 50% compared to PTSEFormer, standing at 5.7 seq/min.

While CVA-Net shows comparable AP50 metrics to our method, UltraDet significantly improves upon both precision and FP rates.

Best regards,
Youcheng Li
