### ISSUE TITLE
Whole network information

### ISSUE THREAD

**Issue by optimisticabouthumanity** [HaojunYu1998/UltraDet#7]
Is it possible to know how many parameters, layers and FLOPs (including backbone and flownet) do the network have as a whole?

**Comment by xjtulyc** [comment]
Our code is based on Detectron2, a popular computer vision library developed by Facebook AI Research. To determine the total number of parameters, layers, and FLOPs for the entire network, including both the backbone and FlowNet components, you can refer to the relevant documentation provided by Detectron2.

**Comment by optimisticabouthumanity** [comment]
@xjtulyc , how many parameters does only the ultradet.pth have?

**Comment by xjtulyc** [comment]
33.06 M, 33059164 in total.
